// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countFeedback = `-- name: CountFeedback :one
SELECT COUNT(*) FROM feedback
`

func (q *Queries) CountFeedback(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeedback)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (user_id, rating, comment, app_version)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, rating, comment, app_version, created_at
`

type CreateFeedbackParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Rating     int16          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	AppVersion sql.NullString `json:"app_version"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback,
		arg.UserID,
		arg.Rating,
		arg.Comment,
		arg.AppVersion,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedbackAdmin = `-- name: ListFeedbackAdmin :many
SELECT f.id, f.user_id, f.rating, f.comment, f.app_version, f.created_at, u.username, u.email
FROM feedback f
JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
LIMIT $1 OFFSET ($2::int * $1)
`

type ListFeedbackAdminParams struct {
	Limit   int32 `json:"limit"`
	Column2 int32 `json:"column_2"`
}

type ListFeedbackAdminRow struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Rating     int16          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	AppVersion sql.NullString `json:"app_version"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
}

func (q *Queries) ListFeedbackAdmin(ctx context.Context, arg ListFeedbackAdminParams) ([]ListFeedbackAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbackAdmin, arg.Limit, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedbackAdminRow
	for rows.Next() {
		var i ListFeedbackAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.AppVersion,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
