// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Feedback struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Rating     int16          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	AppVersion sql.NullString `json:"app_version"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type User struct {
	ID               uuid.UUID      `json:"id"`
	Username         string         `json:"username"`
	Email            string         `json:"email"`
	PasswordHash     string         `json:"password_hash"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	PhonkLevel       sql.NullString `json:"phonk_level"`
	IsVerified       sql.NullBool   `json:"is_verified"`
	VerificationCode sql.NullString `json:"verification_code"`
	CodeExpiresAt    sql.NullTime   `json:"code_expires_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	IsBanned         bool           `json:"is_banned"`
	BannedAt         sql.NullTime   `json:"banned_at"`
	BanReason        sql.NullString `json:"ban_reason"`
	FcmToken         sql.NullString `json:"fcm_token"`
}
