// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, dollar_1 string) (User, error)
	GetVerificationDetails(ctx context.Context, dollar_1 string) (GetVerificationDetailsRow, error)
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error)
}

var _ Querier = (*Queries)(nil)
