// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const banUser = `-- name: BanUser :exec
UPDATE users 
SET is_banned = true, banned_at = NOW(), ban_reason = $2
WHERE id = $1
`

type BanUserParams struct {
	ID        uuid.UUID      `json:"id"`
	BanReason sql.NullString `json:"ban_reason"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.ExecContext(ctx, banUser, arg.ID, arg.BanReason)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, verification_code, code_expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, avatar_url, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	Username         string         `json:"username"`
	Email            string         `json:"email"`
	PasswordHash     string         `json:"password_hash"`
	VerificationCode sql.NullString `json:"verification_code"`
	CodeExpiresAt    sql.NullTime   `json:"code_expires_at"`
}

type CreateUserRow struct {
	ID         uuid.UUID      `json:"id"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	IsVerified sql.NullBool   `json:"is_verified"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.VerificationCode,
		arg.CodeExpiresAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, avatar_url, phonk_level, is_verified, verification_code, code_expires_at, created_at, updated_at, is_banned, banned_at, ban_reason, fcm_token FROM users
WHERE email = $1::text LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.PhonkLevel,
		&i.IsVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanned,
		&i.BannedAt,
		&i.BanReason,
		&i.FcmToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, avatar_url, phonk_level, is_verified, verification_code, code_expires_at, created_at, updated_at, is_banned, banned_at, ban_reason, fcm_token FROM users
WHERE id = $1::uuid LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.PhonkLevel,
		&i.IsVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanned,
		&i.BannedAt,
		&i.BanReason,
		&i.FcmToken,
	)
	return i, err
}

const getUserFCMTokens = `-- name: GetUserFCMTokens :many
SELECT fcm_token FROM users
WHERE is_banned = false AND fcm_token IS NOT NULL AND fcm_token != ''
`

func (q *Queries) GetUserFCMTokens(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getUserFCMTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var fcm_token sql.NullString
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerificationDetails = `-- name: GetVerificationDetails :one
SELECT id, verification_code, code_expires_at, is_verified
FROM users
WHERE email = $1::text LIMIT 1
`

type GetVerificationDetailsRow struct {
	ID               uuid.UUID      `json:"id"`
	VerificationCode sql.NullString `json:"verification_code"`
	CodeExpiresAt    sql.NullTime   `json:"code_expires_at"`
	IsVerified       sql.NullBool   `json:"is_verified"`
}

func (q *Queries) GetVerificationDetails(ctx context.Context, dollar_1 string) (GetVerificationDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getVerificationDetails, dollar_1)
	var i GetVerificationDetailsRow
	err := row.Scan(
		&i.ID,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.IsVerified,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users 
SET is_banned = false, banned_at = NULL, ban_reason = NULL
WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unbanUser, id)
	return err
}

const updateAvatarURL = `-- name: UpdateAvatarURL :one
UPDATE users
SET avatar_url = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, avatar_url, phonk_level, is_verified, verification_code, code_expires_at, created_at, updated_at, is_banned, banned_at, ban_reason, fcm_token
`

type UpdateAvatarURLParams struct {
	ID        uuid.UUID      `json:"id"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateAvatarURL(ctx context.Context, arg UpdateAvatarURLParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateAvatarURL, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.PhonkLevel,
		&i.IsVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanned,
		&i.BannedAt,
		&i.BanReason,
		&i.FcmToken,
	)
	return i, err
}

const updateFCMToken = `-- name: UpdateFCMToken :exec
UPDATE users SET fcm_token = $2 WHERE id = $1
`

type UpdateFCMTokenParams struct {
	ID       uuid.UUID      `json:"id"`
	FcmToken sql.NullString `json:"fcm_token"`
}

func (q *Queries) UpdateFCMToken(ctx context.Context, arg UpdateFCMTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateFCMToken, arg.ID, arg.FcmToken)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $1::text,
    verification_code = NULL,
    code_expires_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid
`

type UpdatePasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPhonkLevel = `-- name: UpdateUserPhonkLevel :one
UPDATE users
SET phonk_level = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, avatar_url, phonk_level, is_verified, verification_code, code_expires_at, created_at, updated_at, is_banned, banned_at, ban_reason, fcm_token
`

type UpdateUserPhonkLevelParams struct {
	ID         uuid.UUID      `json:"id"`
	PhonkLevel sql.NullString `json:"phonk_level"`
}

func (q *Queries) UpdateUserPhonkLevel(ctx context.Context, arg UpdateUserPhonkLevelParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPhonkLevel, arg.ID, arg.PhonkLevel)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.PhonkLevel,
		&i.IsVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanned,
		&i.BannedAt,
		&i.BanReason,
		&i.FcmToken,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE users
SET is_verified = $1::boolean, 
    verification_code = NULL, 
    code_expires_at = NULL, 
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid
RETURNING id, username, email, password_hash, avatar_url, phonk_level, is_verified, verification_code, code_expires_at, created_at, updated_at, is_banned, banned_at, ban_reason, fcm_token
`

type UpdateUserVerificationParams struct {
	IsVerified bool      `json:"is_verified"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserVerification, arg.IsVerified, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.PhonkLevel,
		&i.IsVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanned,
		&i.BannedAt,
		&i.BanReason,
		&i.FcmToken,
	)
	return i, err
}

const updateUserVerificationCode = `-- name: UpdateUserVerificationCode :exec
UPDATE users
SET verification_code = $1::text,
    code_expires_at = $2::timestamptz,
    updated_at = CURRENT_TIMESTAMP
WHERE email = $3::text
`

type UpdateUserVerificationCodeParams struct {
	VerificationCode string    `json:"verification_code"`
	CodeExpiresAt    time.Time `json:"code_expires_at"`
	Email            string    `json:"email"`
}

func (q *Queries) UpdateUserVerificationCode(ctx context.Context, arg UpdateUserVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerificationCode, arg.VerificationCode, arg.CodeExpiresAt, arg.Email)
	return err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users
SET username = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, avatar_url, phonk_level, is_verified, verification_code, code_expires_at, created_at, updated_at, is_banned, banned_at, ban_reason, fcm_token
`

type UpdateUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.PhonkLevel,
		&i.IsVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBanned,
		&i.BannedAt,
		&i.BanReason,
		&i.FcmToken,
	)
	return i, err
}
