// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, username, email, avatar_url, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID         uuid.UUID      `json:"id"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	IsVerified sql.NullBool   `json:"is_verified"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, avatar_url, is_verified, created_at, updated_at FROM users
WHERE email = $1::text LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE users
SET is_verified = $1::boolean, updated_at = CURRENT_TIMESTAMP
WHERE id = $2::uuid
RETURNING id, username, email, password_hash, avatar_url, is_verified, created_at, updated_at
`

type UpdateUserVerificationParams struct {
	Column1 bool      `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserVerification, arg.Column1, arg.Column2)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
