// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: track/track.proto

package trackpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackService_SearchTrack_FullMethodName       = "/track.TrackService/SearchTrack"
	TrackService_GetStreamURL_FullMethodName      = "/track.TrackService/GetStreamURL"
	TrackService_GetTrendingTracks_FullMethodName = "/track.TrackService/GetTrendingTracks"
)

// TrackServiceClient is the client API for TrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service handling music discovery, streaming links, and trend triggers
type TrackServiceClient interface {
	// Client searches for a Phonk track
	SearchTrack(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Fetches the direct, temporary streaming link (handled by Go + yt-dlp)
	GetStreamURL(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error)
	// Fetches top trending tracks to display on the home screen
	GetTrendingTracks(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error)
}

type trackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackServiceClient(cc grpc.ClientConnInterface) TrackServiceClient {
	return &trackServiceClient{cc}
}

func (c *trackServiceClient) SearchTrack(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, TrackService_SearchTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetStreamURL(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamResponse)
	err := c.cc.Invoke(ctx, TrackService_GetStreamURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetTrendingTracks(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingResponse)
	err := c.cc.Invoke(ctx, TrackService_GetTrendingTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackServiceServer is the server API for TrackService service.
// All implementations must embed UnimplementedTrackServiceServer
// for forward compatibility.
//
// Service handling music discovery, streaming links, and trend triggers
type TrackServiceServer interface {
	// Client searches for a Phonk track
	SearchTrack(context.Context, *SearchRequest) (*SearchResponse, error)
	// Fetches the direct, temporary streaming link (handled by Go + yt-dlp)
	GetStreamURL(context.Context, *StreamRequest) (*StreamResponse, error)
	// Fetches top trending tracks to display on the home screen
	GetTrendingTracks(context.Context, *TrendingRequest) (*TrendingResponse, error)
	mustEmbedUnimplementedTrackServiceServer()
}

// UnimplementedTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackServiceServer struct{}

func (UnimplementedTrackServiceServer) SearchTrack(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTrack not implemented")
}
func (UnimplementedTrackServiceServer) GetStreamURL(context.Context, *StreamRequest) (*StreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamURL not implemented")
}
func (UnimplementedTrackServiceServer) GetTrendingTracks(context.Context, *TrendingRequest) (*TrendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingTracks not implemented")
}
func (UnimplementedTrackServiceServer) mustEmbedUnimplementedTrackServiceServer() {}
func (UnimplementedTrackServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackServiceServer will
// result in compilation errors.
type UnsafeTrackServiceServer interface {
	mustEmbedUnimplementedTrackServiceServer()
}

func RegisterTrackServiceServer(s grpc.ServiceRegistrar, srv TrackServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackService_ServiceDesc, srv)
}

func _TrackService_SearchTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).SearchTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_SearchTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).SearchTrack(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetStreamURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetStreamURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetStreamURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetStreamURL(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetTrendingTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetTrendingTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetTrendingTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetTrendingTracks(ctx, req.(*TrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackService_ServiceDesc is the grpc.ServiceDesc for TrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "track.TrackService",
	HandlerType: (*TrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTrack",
			Handler:    _TrackService_SearchTrack_Handler,
		},
		{
			MethodName: "GetStreamURL",
			Handler:    _TrackService_GetStreamURL_Handler,
		},
		{
			MethodName: "GetTrendingTracks",
			Handler:    _TrackService_GetTrendingTracks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "track/track.proto",
}
