// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: track/track.proto

package trackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackId           string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist            string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Duration          string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	ThumbnailUrl      string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	OriginalYoutubeId string                 `protobuf:"bytes,6,opt,name=original_youtube_id,json=originalYoutubeId,proto3" json:"original_youtube_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackMetadata) Reset() {
	*x = TrackMetadata{}
	mi := &file_track_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackMetadata) ProtoMessage() {}

func (x *TrackMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackMetadata.ProtoReflect.Descriptor instead.
func (*TrackMetadata) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{0}
}

func (x *TrackMetadata) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *TrackMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackMetadata) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *TrackMetadata) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TrackMetadata) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *TrackMetadata) GetOriginalYoutubeId() string {
	if x != nil {
		return x.OriginalYoutubeId
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_track_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"` // "repeated" means an Array/List in Dart/Go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_track_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type StreamRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackId           string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	OriginalYoutubeId string                 `protobuf:"bytes,2,opt,name=original_youtube_id,json=originalYoutubeId,proto3" json:"original_youtube_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_track_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *StreamRequest) GetOriginalYoutubeId() string {
	if x != nil {
		return x.OriginalYoutubeId
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`                // The high-speed direct stream link
	LinkExpiresAt int64                  `protobuf:"varint,2,opt,name=link_expires_at,json=linkExpiresAt,proto3" json:"link_expires_at,omitempty"` // Unix timestamp when the link dies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_track_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{4}
}

func (x *StreamResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *StreamResponse) GetLinkExpiresAt() int64 {
	if x != nil {
		return x.LinkExpiresAt
	}
	return 0
}

type TrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingRequest) Reset() {
	*x = TrendingRequest{}
	mi := &file_track_track_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingRequest) ProtoMessage() {}

func (x *TrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingRequest.ProtoReflect.Descriptor instead.
func (*TrendingRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{5}
}

func (x *TrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingResponse) Reset() {
	*x = TrendingResponse{}
	mi := &file_track_track_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingResponse) ProtoMessage() {}

func (x *TrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingResponse.ProtoReflect.Descriptor instead.
func (*TrendingResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

var File_track_track_proto protoreflect.FileDescriptor

const file_track_track_proto_rawDesc = "" +
	"\n" +
	"\x11track/track.proto\x12\x05track\"\xc9\x01\n" +
	"\rTrackMetadata\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12.\n" +
	"\x13original_youtube_id\x18\x06 \x01(\tR\x11originalYoutubeId\"9\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\">\n" +
	"\x0eSearchResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\"Z\n" +
	"\rStreamRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12.\n" +
	"\x13original_youtube_id\x18\x02 \x01(\tR\x11originalYoutubeId\"W\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12&\n" +
	"\x0flink_expires_at\x18\x02 \x01(\x03R\rlinkExpiresAt\"'\n" +
	"\x0fTrendingRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"@\n" +
	"\x10TrendingResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks2\xcd\x01\n" +
	"\fTrackService\x12:\n" +
	"\vSearchTrack\x12\x14.track.SearchRequest\x1a\x15.track.SearchResponse\x12;\n" +
	"\fGetStreamURL\x12\x14.track.StreamRequest\x1a\x15.track.StreamResponse\x12D\n" +
	"\x11GetTrendingTracks\x12\x16.track.TrendingRequest\x1a\x17.track.TrendingResponseB?Z=github.com/fanyicharllson/phonkdrift-backend/pb/track;trackpbb\x06proto3"

var (
	file_track_track_proto_rawDescOnce sync.Once
	file_track_track_proto_rawDescData []byte
)

func file_track_track_proto_rawDescGZIP() []byte {
	file_track_track_proto_rawDescOnce.Do(func() {
		file_track_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_track_track_proto_rawDesc), len(file_track_track_proto_rawDesc)))
	})
	return file_track_track_proto_rawDescData
}

var file_track_track_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_track_track_proto_goTypes = []any{
	(*TrackMetadata)(nil),    // 0: track.TrackMetadata
	(*SearchRequest)(nil),    // 1: track.SearchRequest
	(*SearchResponse)(nil),   // 2: track.SearchResponse
	(*StreamRequest)(nil),    // 3: track.StreamRequest
	(*StreamResponse)(nil),   // 4: track.StreamResponse
	(*TrendingRequest)(nil),  // 5: track.TrendingRequest
	(*TrendingResponse)(nil), // 6: track.TrendingResponse
}
var file_track_track_proto_depIdxs = []int32{
	0, // 0: track.SearchResponse.tracks:type_name -> track.TrackMetadata
	0, // 1: track.TrendingResponse.tracks:type_name -> track.TrackMetadata
	1, // 2: track.TrackService.SearchTrack:input_type -> track.SearchRequest
	3, // 3: track.TrackService.GetStreamURL:input_type -> track.StreamRequest
	5, // 4: track.TrackService.GetTrendingTracks:input_type -> track.TrendingRequest
	2, // 5: track.TrackService.SearchTrack:output_type -> track.SearchResponse
	4, // 6: track.TrackService.GetStreamURL:output_type -> track.StreamResponse
	6, // 7: track.TrackService.GetTrendingTracks:output_type -> track.TrendingResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_track_track_proto_init() }
func file_track_track_proto_init() {
	if File_track_track_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_track_track_proto_rawDesc), len(file_track_track_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_track_track_proto_goTypes,
		DependencyIndexes: file_track_track_proto_depIdxs,
		MessageInfos:      file_track_track_proto_msgTypes,
	}.Build()
	File_track_track_proto = out.File
	file_track_track_proto_goTypes = nil
	file_track_track_proto_depIdxs = nil
}
