// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: track/track.proto

package trackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_track_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{0}
}

type TrackMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackId           string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistId          string                 `protobuf:"bytes,3,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	ArtistName        string                 `protobuf:"bytes,4,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Duration          string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	ThumbnailUrl      string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	OriginalYoutubeId string                 `protobuf:"bytes,7,opt,name=original_youtube_id,json=originalYoutubeId,proto3" json:"original_youtube_id,omitempty"`
	PlayCount         int32                  `protobuf:"varint,8,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	LikesCount        int32                  `protobuf:"varint,9,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	StorageUrl        string                 `protobuf:"bytes,10,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"` // — DO Spaces CDN URL
	Genre             string                 `protobuf:"bytes,11,opt,name=genre,proto3" json:"genre,omitempty"`
	IsFeatured        bool                   `protobuf:"varint,12,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsApproved        bool                   `protobuf:"varint,13,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	Source            string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"` //  — "auto" | "manual"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackMetadata) Reset() {
	*x = TrackMetadata{}
	mi := &file_track_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackMetadata) ProtoMessage() {}

func (x *TrackMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackMetadata.ProtoReflect.Descriptor instead.
func (*TrackMetadata) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{1}
}

func (x *TrackMetadata) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *TrackMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackMetadata) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *TrackMetadata) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *TrackMetadata) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TrackMetadata) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *TrackMetadata) GetOriginalYoutubeId() string {
	if x != nil {
		return x.OriginalYoutubeId
	}
	return ""
}

func (x *TrackMetadata) GetPlayCount() int32 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *TrackMetadata) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *TrackMetadata) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

func (x *TrackMetadata) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *TrackMetadata) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *TrackMetadata) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *TrackMetadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_track_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_track_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type StreamRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackId           string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	OriginalYoutubeId string                 `protobuf:"bytes,2,opt,name=original_youtube_id,json=originalYoutubeId,proto3" json:"original_youtube_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_track_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *StreamRequest) GetOriginalYoutubeId() string {
	if x != nil {
		return x.OriginalYoutubeId
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	LinkExpiresAt int64                  `protobuf:"varint,2,opt,name=link_expires_at,json=linkExpiresAt,proto3" json:"link_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_track_track_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{5}
}

func (x *StreamResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *StreamResponse) GetLinkExpiresAt() int64 {
	if x != nil {
		return x.LinkExpiresAt
	}
	return 0
}

type TrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingRequest) Reset() {
	*x = TrendingRequest{}
	mi := &file_track_track_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingRequest) ProtoMessage() {}

func (x *TrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingRequest.ProtoReflect.Descriptor instead.
func (*TrendingRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingResponse) Reset() {
	*x = TrendingResponse{}
	mi := &file_track_track_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingResponse) ProtoMessage() {}

func (x *TrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingResponse.ProtoReflect.Descriptor instead.
func (*TrendingResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{7}
}

func (x *TrendingResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type PlaybackTelemetryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackId             string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	LastPositionSeconds int32                  `protobuf:"varint,3,opt,name=last_position_seconds,json=lastPositionSeconds,proto3" json:"last_position_seconds,omitempty"`
	IsCompleted         bool                   `protobuf:"varint,4,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlaybackTelemetryRequest) Reset() {
	*x = PlaybackTelemetryRequest{}
	mi := &file_track_track_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackTelemetryRequest) ProtoMessage() {}

func (x *PlaybackTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackTelemetryRequest.ProtoReflect.Descriptor instead.
func (*PlaybackTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{8}
}

func (x *PlaybackTelemetryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaybackTelemetryRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *PlaybackTelemetryRequest) GetLastPositionSeconds() int32 {
	if x != nil {
		return x.LastPositionSeconds
	}
	return 0
}

func (x *PlaybackTelemetryRequest) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type PlaybackTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackTelemetryResponse) Reset() {
	*x = PlaybackTelemetryResponse{}
	mi := &file_track_track_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackTelemetryResponse) ProtoMessage() {}

func (x *PlaybackTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackTelemetryResponse.ProtoReflect.Descriptor instead.
func (*PlaybackTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{9}
}

func (x *PlaybackTelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RecentlyPlayedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentlyPlayedRequest) Reset() {
	*x = RecentlyPlayedRequest{}
	mi := &file_track_track_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentlyPlayedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentlyPlayedRequest) ProtoMessage() {}

func (x *RecentlyPlayedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentlyPlayedRequest.ProtoReflect.Descriptor instead.
func (*RecentlyPlayedRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{10}
}

func (x *RecentlyPlayedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecentlyPlayedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentlyPlayedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentlyPlayedResponse) Reset() {
	*x = RecentlyPlayedResponse{}
	mi := &file_track_track_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentlyPlayedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentlyPlayedResponse) ProtoMessage() {}

func (x *RecentlyPlayedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentlyPlayedResponse.ProtoReflect.Descriptor instead.
func (*RecentlyPlayedResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{11}
}

func (x *RecentlyPlayedResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type InteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	IsLiked       bool                   `protobuf:"varint,3,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionRequest) Reset() {
	*x = InteractionRequest{}
	mi := &file_track_track_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRequest) ProtoMessage() {}

func (x *InteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRequest.ProtoReflect.Descriptor instead.
func (*InteractionRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{12}
}

func (x *InteractionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InteractionRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *InteractionRequest) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type InteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionResponse) Reset() {
	*x = InteractionResponse{}
	mi := &file_track_track_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionResponse) ProtoMessage() {}

func (x *InteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionResponse.ProtoReflect.Descriptor instead.
func (*InteractionResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{13}
}

func (x *InteractionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistRequest) Reset() {
	*x = CreatePlaylistRequest{}
	mi := &file_track_track_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRequest) ProtoMessage() {}

func (x *CreatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePlaylistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlaylistRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

type PlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistResponse) Reset() {
	*x = PlaylistResponse{}
	mi := &file_track_track_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistResponse) ProtoMessage() {}

func (x *PlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistResponse.ProtoReflect.Descriptor instead.
func (*PlaylistResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{15}
}

func (x *PlaylistResponse) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *PlaylistResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaylistResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaylistResponse) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

type PlaylistTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified session; used for ownership check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistTrackRequest) Reset() {
	*x = PlaylistTrackRequest{}
	mi := &file_track_track_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistTrackRequest) ProtoMessage() {}

func (x *PlaylistTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistTrackRequest.ProtoReflect.Descriptor instead.
func (*PlaylistTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{16}
}

func (x *PlaylistTrackRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *PlaylistTrackRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *PlaylistTrackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PlaylistActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistActionResponse) Reset() {
	*x = PlaylistActionResponse{}
	mi := &file_track_track_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistActionResponse) ProtoMessage() {}

func (x *PlaylistActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistActionResponse.ProtoReflect.Descriptor instead.
func (*PlaylistActionResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{17}
}

func (x *PlaylistActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaylistActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified session; used for the privacy check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistRequest) Reset() {
	*x = GetPlaylistRequest{}
	mi := &file_track_track_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistRequest) ProtoMessage() {}

func (x *GetPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlaylistRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetPlaylistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,6,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistResponse) Reset() {
	*x = GetPlaylistResponse{}
	mi := &file_track_track_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistResponse) ProtoMessage() {}

func (x *GetPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{19}
}

func (x *GetPlaylistResponse) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetPlaylistResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPlaylistResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPlaylistResponse) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *GetPlaylistResponse) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *GetPlaylistResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetUserPlaylistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPlaylistsRequest) Reset() {
	*x = GetUserPlaylistsRequest{}
	mi := &file_track_track_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPlaylistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlaylistsRequest) ProtoMessage() {}

func (x *GetUserPlaylistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlaylistsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPlaylistsRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserPlaylistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PlaylistSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	TrackCount    int32                  `protobuf:"varint,5,opt,name=track_count,json=trackCount,proto3" json:"track_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistSummary) Reset() {
	*x = PlaylistSummary{}
	mi := &file_track_track_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistSummary) ProtoMessage() {}

func (x *PlaylistSummary) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistSummary.ProtoReflect.Descriptor instead.
func (*PlaylistSummary) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{21}
}

func (x *PlaylistSummary) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *PlaylistSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaylistSummary) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *PlaylistSummary) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *PlaylistSummary) GetTrackCount() int32 {
	if x != nil {
		return x.TrackCount
	}
	return 0
}

type GetUserPlaylistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*PlaylistSummary     `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPlaylistsResponse) Reset() {
	*x = GetUserPlaylistsResponse{}
	mi := &file_track_track_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPlaylistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlaylistsResponse) ProtoMessage() {}

func (x *GetUserPlaylistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlaylistsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPlaylistsResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserPlaylistsResponse) GetPlaylists() []*PlaylistSummary {
	if x != nil {
		return x.Playlists
	}
	return nil
}

// — ForYou feed
type ForYouRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForYouRequest) Reset() {
	*x = ForYouRequest{}
	mi := &file_track_track_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForYouRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForYouRequest) ProtoMessage() {}

func (x *ForYouRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForYouRequest.ProtoReflect.Descriptor instead.
func (*ForYouRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{23}
}

func (x *ForYouRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ForYouRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ForYouResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForYouResponse) Reset() {
	*x = ForYouResponse{}
	mi := &file_track_track_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForYouResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForYouResponse) ProtoMessage() {}

func (x *ForYouResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForYouResponse.ProtoReflect.Descriptor instead.
func (*ForYouResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{24}
}

func (x *ForYouResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

// — Admin messages
type SeedTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YoutubeId     string                 `protobuf:"bytes,1,opt,name=youtube_id,json=youtubeId,proto3" json:"youtube_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistName    string                 `protobuf:"bytes,3,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	StorageUrl    string                 `protobuf:"bytes,6,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedTrackRequest) Reset() {
	*x = SeedTrackRequest{}
	mi := &file_track_track_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedTrackRequest) ProtoMessage() {}

func (x *SeedTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedTrackRequest.ProtoReflect.Descriptor instead.
func (*SeedTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{25}
}

func (x *SeedTrackRequest) GetYoutubeId() string {
	if x != nil {
		return x.YoutubeId
	}
	return ""
}

func (x *SeedTrackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SeedTrackRequest) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *SeedTrackRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SeedTrackRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *SeedTrackRequest) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

type SeedTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	StorageUrl    string                 `protobuf:"bytes,2,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedTrackResponse) Reset() {
	*x = SeedTrackResponse{}
	mi := &file_track_track_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedTrackResponse) ProtoMessage() {}

func (x *SeedTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedTrackResponse.ProtoReflect.Descriptor instead.
func (*SeedTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{26}
}

func (x *SeedTrackResponse) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *SeedTrackResponse) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

type ListTracksAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracksAdminRequest) Reset() {
	*x = ListTracksAdminRequest{}
	mi := &file_track_track_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracksAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracksAdminRequest) ProtoMessage() {}

func (x *ListTracksAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracksAdminRequest.ProtoReflect.Descriptor instead.
func (*ListTracksAdminRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{27}
}

func (x *ListTracksAdminRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTracksAdminRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTracksAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracksAdminResponse) Reset() {
	*x = ListTracksAdminResponse{}
	mi := &file_track_track_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracksAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracksAdminResponse) ProtoMessage() {}

func (x *ListTracksAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracksAdminResponse.ProtoReflect.Descriptor instead.
func (*ListTracksAdminResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{28}
}

func (x *ListTracksAdminResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *ListTracksAdminResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TrackActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackActionRequest) Reset() {
	*x = TrackActionRequest{}
	mi := &file_track_track_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackActionRequest) ProtoMessage() {}

func (x *TrackActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackActionRequest.ProtoReflect.Descriptor instead.
func (*TrackActionRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{29}
}

func (x *TrackActionRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type TrackActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackActionResponse) Reset() {
	*x = TrackActionResponse{}
	mi := &file_track_track_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackActionResponse) ProtoMessage() {}

func (x *TrackActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackActionResponse.ProtoReflect.Descriptor instead.
func (*TrackActionResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{30}
}

func (x *TrackActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FeatureTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,2,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureTrackRequest) Reset() {
	*x = FeatureTrackRequest{}
	mi := &file_track_track_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureTrackRequest) ProtoMessage() {}

func (x *FeatureTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureTrackRequest.ProtoReflect.Descriptor instead.
func (*FeatureTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{31}
}

func (x *FeatureTrackRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *FeatureTrackRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

type AdminStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTracks   int32                  `protobuf:"varint,1,opt,name=total_tracks,json=totalTracks,proto3" json:"total_tracks,omitempty"`
	TotalPlays    int32                  `protobuf:"varint,2,opt,name=total_plays,json=totalPlays,proto3" json:"total_plays,omitempty"`
	PendingTracks int32                  `protobuf:"varint,3,opt,name=pending_tracks,json=pendingTracks,proto3" json:"pending_tracks,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,4,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatsResponse) Reset() {
	*x = AdminStatsResponse{}
	mi := &file_track_track_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsResponse) ProtoMessage() {}

func (x *AdminStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsResponse.ProtoReflect.Descriptor instead.
func (*AdminStatsResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{32}
}

func (x *AdminStatsResponse) GetTotalTracks() int32 {
	if x != nil {
		return x.TotalTracks
	}
	return 0
}

func (x *AdminStatsResponse) GetTotalPlays() int32 {
	if x != nil {
		return x.TotalPlays
	}
	return 0
}

func (x *AdminStatsResponse) GetPendingTracks() int32 {
	if x != nil {
		return x.PendingTracks
	}
	return 0
}

func (x *AdminStatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

type GetLikedTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikedTracksRequest) Reset() {
	*x = GetLikedTracksRequest{}
	mi := &file_track_track_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikedTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikedTracksRequest) ProtoMessage() {}

func (x *GetLikedTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikedTracksRequest.ProtoReflect.Descriptor instead.
func (*GetLikedTracksRequest) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{33}
}

func (x *GetLikedTracksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLikedTracksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLikedTracksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetLikedTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*TrackMetadata       `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikedTracksResponse) Reset() {
	*x = GetLikedTracksResponse{}
	mi := &file_track_track_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikedTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikedTracksResponse) ProtoMessage() {}

func (x *GetLikedTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_track_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikedTracksResponse.ProtoReflect.Descriptor instead.
func (*GetLikedTracksResponse) Descriptor() ([]byte, []int) {
	return file_track_track_proto_rawDescGZIP(), []int{34}
}

func (x *GetLikedTracksResponse) GetTracks() []*TrackMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *GetLikedTracksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_track_track_proto protoreflect.FileDescriptor

const file_track_track_proto_rawDesc = "" +
	"\n" +
	"\x11track/track.proto\x12\x05track\"\a\n" +
	"\x05Empty\"\xc0\x03\n" +
	"\rTrackMetadata\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tartist_id\x18\x03 \x01(\tR\bartistId\x12\x1f\n" +
	"\vartist_name\x18\x04 \x01(\tR\n" +
	"artistName\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12.\n" +
	"\x13original_youtube_id\x18\a \x01(\tR\x11originalYoutubeId\x12\x1d\n" +
	"\n" +
	"play_count\x18\b \x01(\x05R\tplayCount\x12\x1f\n" +
	"\vlikes_count\x18\t \x01(\x05R\n" +
	"likesCount\x12\x1f\n" +
	"\vstorage_url\x18\n" +
	" \x01(\tR\n" +
	"storageUrl\x12\x14\n" +
	"\x05genre\x18\v \x01(\tR\x05genre\x12\x1f\n" +
	"\vis_featured\x18\f \x01(\bR\n" +
	"isFeatured\x12\x1f\n" +
	"\vis_approved\x18\r \x01(\bR\n" +
	"isApproved\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\"9\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\">\n" +
	"\x0eSearchResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\"Z\n" +
	"\rStreamRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12.\n" +
	"\x13original_youtube_id\x18\x02 \x01(\tR\x11originalYoutubeId\"W\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12&\n" +
	"\x0flink_expires_at\x18\x02 \x01(\x03R\rlinkExpiresAt\"'\n" +
	"\x0fTrendingRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"@\n" +
	"\x10TrendingResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\"\xa5\x01\n" +
	"\x18PlaybackTelemetryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x122\n" +
	"\x15last_position_seconds\x18\x03 \x01(\x05R\x13lastPositionSeconds\x12!\n" +
	"\fis_completed\x18\x04 \x01(\bR\visCompleted\"5\n" +
	"\x19PlaybackTelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x15RecentlyPlayedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x16RecentlyPlayedResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\"c\n" +
	"\x12InteractionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12\x19\n" +
	"\bis_liked\x18\x03 \x01(\bR\aisLiked\"/\n" +
	"\x13InteractionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\x15CreatePlaylistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\"\x88\x01\n" +
	"\x10PlaylistResponse\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\"k\n" +
	"\x14PlaylistTrackRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"L\n" +
	"\x16PlaylistActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x12GetPlaylistRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xd8\x01\n" +
	"\x13GetPlaylistResponse\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12\x1d\n" +
	"\n" +
	"is_private\x18\x05 \x01(\bR\tisPrivate\x12,\n" +
	"\x06tracks\x18\x06 \x03(\v2\x14.track.TrackMetadataR\x06tracks\"2\n" +
	"\x17GetUserPlaylistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xae\x01\n" +
	"\x0fPlaylistSummary\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x1f\n" +
	"\vtrack_count\x18\x05 \x01(\x05R\n" +
	"trackCount\"P\n" +
	"\x18GetUserPlaylistsResponse\x124\n" +
	"\tplaylists\x18\x01 \x03(\v2\x16.track.PlaylistSummaryR\tplaylists\">\n" +
	"\rForYouRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\">\n" +
	"\x0eForYouResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\"\xc4\x01\n" +
	"\x10SeedTrackRequest\x12\x1d\n" +
	"\n" +
	"youtube_id\x18\x01 \x01(\tR\tyoutubeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vartist_name\x18\x03 \x01(\tR\n" +
	"artistName\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12\x1f\n" +
	"\vstorage_url\x18\x06 \x01(\tR\n" +
	"storageUrl\"O\n" +
	"\x11SeedTrackResponse\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x1f\n" +
	"\vstorage_url\x18\x02 \x01(\tR\n" +
	"storageUrl\"B\n" +
	"\x16ListTracksAdminRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"]\n" +
	"\x17ListTracksAdminResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x12TrackActionRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\"I\n" +
	"\x13TrackActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\x13FeatureTrackRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x1f\n" +
	"\vis_featured\x18\x02 \x01(\bR\n" +
	"isFeatured\"\xa0\x01\n" +
	"\x12AdminStatsResponse\x12!\n" +
	"\ftotal_tracks\x18\x01 \x01(\x05R\vtotalTracks\x12\x1f\n" +
	"\vtotal_plays\x18\x02 \x01(\x05R\n" +
	"totalPlays\x12%\n" +
	"\x0epending_tracks\x18\x03 \x01(\x05R\rpendingTracks\x12\x1f\n" +
	"\vtotal_users\x18\x04 \x01(\x05R\n" +
	"totalUsers\"Z\n" +
	"\x15GetLikedTracksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\\\n" +
	"\x16GetLikedTracksResponse\x12,\n" +
	"\x06tracks\x18\x01 \x03(\v2\x14.track.TrackMetadataR\x06tracks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xea\n" +
	"\n" +
	"\fTrackService\x12:\n" +
	"\vSearchTrack\x12\x14.track.SearchRequest\x1a\x15.track.SearchResponse\x12;\n" +
	"\fGetStreamURL\x12\x14.track.StreamRequest\x1a\x15.track.StreamResponse\x12D\n" +
	"\x11GetTrendingTracks\x12\x16.track.TrendingRequest\x1a\x17.track.TrendingResponse\x128\n" +
	"\tGetForYou\x12\x14.track.ForYouRequest\x1a\x15.track.ForYouResponse\x12Z\n" +
	"\x15SyncPlaybackTelemetry\x12\x1f.track.PlaybackTelemetryRequest\x1a .track.PlaybackTelemetryResponse\x12P\n" +
	"\x11GetRecentlyPlayed\x12\x1c.track.RecentlyPlayedRequest\x1a\x1d.track.RecentlyPlayedResponse\x12L\n" +
	"\x13SetTrackInteraction\x12\x19.track.InteractionRequest\x1a\x1a.track.InteractionResponse\x12G\n" +
	"\x0eCreatePlaylist\x12\x1c.track.CreatePlaylistRequest\x1a\x17.track.PlaylistResponse\x12K\n" +
	"\rAddToPlaylist\x12\x1b.track.PlaylistTrackRequest\x1a\x1d.track.PlaylistActionResponse\x12D\n" +
	"\vGetPlaylist\x12\x19.track.GetPlaylistRequest\x1a\x1a.track.GetPlaylistResponse\x12S\n" +
	"\x10GetUserPlaylists\x12\x1e.track.GetUserPlaylistsRequest\x1a\x1f.track.GetUserPlaylistsResponse\x12>\n" +
	"\tSeedTrack\x12\x17.track.SeedTrackRequest\x1a\x18.track.SeedTrackResponse\x12P\n" +
	"\x0fListTracksAdmin\x12\x1d.track.ListTracksAdminRequest\x1a\x1e.track.ListTracksAdminResponse\x12E\n" +
	"\fApproveTrack\x12\x19.track.TrackActionRequest\x1a\x1a.track.TrackActionResponse\x12D\n" +
	"\vRejectTrack\x12\x19.track.TrackActionRequest\x1a\x1a.track.TrackActionResponse\x12F\n" +
	"\fFeatureTrack\x12\x1a.track.FeatureTrackRequest\x1a\x1a.track.TrackActionResponse\x12D\n" +
	"\vDeleteTrack\x12\x19.track.TrackActionRequest\x1a\x1a.track.TrackActionResponse\x128\n" +
	"\rGetAdminStats\x12\f.track.Empty\x1a\x19.track.AdminStatsResponse\x12M\n" +
	"\x0eGetLikedTracks\x12\x1c.track.GetLikedTracksRequest\x1a\x1d.track.GetLikedTracksResponseB?Z=github.com/fanyicharllson/phonkdrift-backend/pb/track;trackpbb\x06proto3"

var (
	file_track_track_proto_rawDescOnce sync.Once
	file_track_track_proto_rawDescData []byte
)

func file_track_track_proto_rawDescGZIP() []byte {
	file_track_track_proto_rawDescOnce.Do(func() {
		file_track_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_track_track_proto_rawDesc), len(file_track_track_proto_rawDesc)))
	})
	return file_track_track_proto_rawDescData
}

var file_track_track_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_track_track_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: track.Empty
	(*TrackMetadata)(nil),             // 1: track.TrackMetadata
	(*SearchRequest)(nil),             // 2: track.SearchRequest
	(*SearchResponse)(nil),            // 3: track.SearchResponse
	(*StreamRequest)(nil),             // 4: track.StreamRequest
	(*StreamResponse)(nil),            // 5: track.StreamResponse
	(*TrendingRequest)(nil),           // 6: track.TrendingRequest
	(*TrendingResponse)(nil),          // 7: track.TrendingResponse
	(*PlaybackTelemetryRequest)(nil),  // 8: track.PlaybackTelemetryRequest
	(*PlaybackTelemetryResponse)(nil), // 9: track.PlaybackTelemetryResponse
	(*RecentlyPlayedRequest)(nil),     // 10: track.RecentlyPlayedRequest
	(*RecentlyPlayedResponse)(nil),    // 11: track.RecentlyPlayedResponse
	(*InteractionRequest)(nil),        // 12: track.InteractionRequest
	(*InteractionResponse)(nil),       // 13: track.InteractionResponse
	(*CreatePlaylistRequest)(nil),     // 14: track.CreatePlaylistRequest
	(*PlaylistResponse)(nil),          // 15: track.PlaylistResponse
	(*PlaylistTrackRequest)(nil),      // 16: track.PlaylistTrackRequest
	(*PlaylistActionResponse)(nil),    // 17: track.PlaylistActionResponse
	(*GetPlaylistRequest)(nil),        // 18: track.GetPlaylistRequest
	(*GetPlaylistResponse)(nil),       // 19: track.GetPlaylistResponse
	(*GetUserPlaylistsRequest)(nil),   // 20: track.GetUserPlaylistsRequest
	(*PlaylistSummary)(nil),           // 21: track.PlaylistSummary
	(*GetUserPlaylistsResponse)(nil),  // 22: track.GetUserPlaylistsResponse
	(*ForYouRequest)(nil),             // 23: track.ForYouRequest
	(*ForYouResponse)(nil),            // 24: track.ForYouResponse
	(*SeedTrackRequest)(nil),          // 25: track.SeedTrackRequest
	(*SeedTrackResponse)(nil),         // 26: track.SeedTrackResponse
	(*ListTracksAdminRequest)(nil),    // 27: track.ListTracksAdminRequest
	(*ListTracksAdminResponse)(nil),   // 28: track.ListTracksAdminResponse
	(*TrackActionRequest)(nil),        // 29: track.TrackActionRequest
	(*TrackActionResponse)(nil),       // 30: track.TrackActionResponse
	(*FeatureTrackRequest)(nil),       // 31: track.FeatureTrackRequest
	(*AdminStatsResponse)(nil),        // 32: track.AdminStatsResponse
	(*GetLikedTracksRequest)(nil),     // 33: track.GetLikedTracksRequest
	(*GetLikedTracksResponse)(nil),    // 34: track.GetLikedTracksResponse
}
var file_track_track_proto_depIdxs = []int32{
	1,  // 0: track.SearchResponse.tracks:type_name -> track.TrackMetadata
	1,  // 1: track.TrendingResponse.tracks:type_name -> track.TrackMetadata
	1,  // 2: track.RecentlyPlayedResponse.tracks:type_name -> track.TrackMetadata
	1,  // 3: track.GetPlaylistResponse.tracks:type_name -> track.TrackMetadata
	21, // 4: track.GetUserPlaylistsResponse.playlists:type_name -> track.PlaylistSummary
	1,  // 5: track.ForYouResponse.tracks:type_name -> track.TrackMetadata
	1,  // 6: track.ListTracksAdminResponse.tracks:type_name -> track.TrackMetadata
	1,  // 7: track.GetLikedTracksResponse.tracks:type_name -> track.TrackMetadata
	2,  // 8: track.TrackService.SearchTrack:input_type -> track.SearchRequest
	4,  // 9: track.TrackService.GetStreamURL:input_type -> track.StreamRequest
	6,  // 10: track.TrackService.GetTrendingTracks:input_type -> track.TrendingRequest
	23, // 11: track.TrackService.GetForYou:input_type -> track.ForYouRequest
	8,  // 12: track.TrackService.SyncPlaybackTelemetry:input_type -> track.PlaybackTelemetryRequest
	10, // 13: track.TrackService.GetRecentlyPlayed:input_type -> track.RecentlyPlayedRequest
	12, // 14: track.TrackService.SetTrackInteraction:input_type -> track.InteractionRequest
	14, // 15: track.TrackService.CreatePlaylist:input_type -> track.CreatePlaylistRequest
	16, // 16: track.TrackService.AddToPlaylist:input_type -> track.PlaylistTrackRequest
	18, // 17: track.TrackService.GetPlaylist:input_type -> track.GetPlaylistRequest
	20, // 18: track.TrackService.GetUserPlaylists:input_type -> track.GetUserPlaylistsRequest
	25, // 19: track.TrackService.SeedTrack:input_type -> track.SeedTrackRequest
	27, // 20: track.TrackService.ListTracksAdmin:input_type -> track.ListTracksAdminRequest
	29, // 21: track.TrackService.ApproveTrack:input_type -> track.TrackActionRequest
	29, // 22: track.TrackService.RejectTrack:input_type -> track.TrackActionRequest
	31, // 23: track.TrackService.FeatureTrack:input_type -> track.FeatureTrackRequest
	29, // 24: track.TrackService.DeleteTrack:input_type -> track.TrackActionRequest
	0,  // 25: track.TrackService.GetAdminStats:input_type -> track.Empty
	33, // 26: track.TrackService.GetLikedTracks:input_type -> track.GetLikedTracksRequest
	3,  // 27: track.TrackService.SearchTrack:output_type -> track.SearchResponse
	5,  // 28: track.TrackService.GetStreamURL:output_type -> track.StreamResponse
	7,  // 29: track.TrackService.GetTrendingTracks:output_type -> track.TrendingResponse
	24, // 30: track.TrackService.GetForYou:output_type -> track.ForYouResponse
	9,  // 31: track.TrackService.SyncPlaybackTelemetry:output_type -> track.PlaybackTelemetryResponse
	11, // 32: track.TrackService.GetRecentlyPlayed:output_type -> track.RecentlyPlayedResponse
	13, // 33: track.TrackService.SetTrackInteraction:output_type -> track.InteractionResponse
	15, // 34: track.TrackService.CreatePlaylist:output_type -> track.PlaylistResponse
	17, // 35: track.TrackService.AddToPlaylist:output_type -> track.PlaylistActionResponse
	19, // 36: track.TrackService.GetPlaylist:output_type -> track.GetPlaylistResponse
	22, // 37: track.TrackService.GetUserPlaylists:output_type -> track.GetUserPlaylistsResponse
	26, // 38: track.TrackService.SeedTrack:output_type -> track.SeedTrackResponse
	28, // 39: track.TrackService.ListTracksAdmin:output_type -> track.ListTracksAdminResponse
	30, // 40: track.TrackService.ApproveTrack:output_type -> track.TrackActionResponse
	30, // 41: track.TrackService.RejectTrack:output_type -> track.TrackActionResponse
	30, // 42: track.TrackService.FeatureTrack:output_type -> track.TrackActionResponse
	30, // 43: track.TrackService.DeleteTrack:output_type -> track.TrackActionResponse
	32, // 44: track.TrackService.GetAdminStats:output_type -> track.AdminStatsResponse
	34, // 45: track.TrackService.GetLikedTracks:output_type -> track.GetLikedTracksResponse
	27, // [27:46] is the sub-list for method output_type
	8,  // [8:27] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_track_track_proto_init() }
func file_track_track_proto_init() {
	if File_track_track_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_track_track_proto_rawDesc), len(file_track_track_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_track_track_proto_goTypes,
		DependencyIndexes: file_track_track_proto_depIdxs,
		MessageInfos:      file_track_track_proto_msgTypes,
	}.Build()
	File_track_track_proto = out.File
	file_track_track_proto_goTypes = nil
	file_track_track_proto_depIdxs = nil
}
