// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: track/track.proto

package trackpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackService_SearchTrack_FullMethodName           = "/track.TrackService/SearchTrack"
	TrackService_GetStreamURL_FullMethodName          = "/track.TrackService/GetStreamURL"
	TrackService_GetTrendingTracks_FullMethodName     = "/track.TrackService/GetTrendingTracks"
	TrackService_SyncPlaybackTelemetry_FullMethodName = "/track.TrackService/SyncPlaybackTelemetry"
	TrackService_GetRecentlyPlayed_FullMethodName     = "/track.TrackService/GetRecentlyPlayed"
	TrackService_SetTrackInteraction_FullMethodName   = "/track.TrackService/SetTrackInteraction"
	TrackService_CreatePlaylist_FullMethodName        = "/track.TrackService/CreatePlaylist"
	TrackService_AddToPlaylist_FullMethodName         = "/track.TrackService/AddToPlaylist"
)

// TrackServiceClient is the client API for TrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service managing track playback metadata, streaming sessions, and user interactions
type TrackServiceClient interface {
	// 🔍 TRACK DISCOVERY LAYER
	SearchTrack(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetStreamURL(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error)
	GetTrendingTracks(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error)
	// 🔄 TELEMETRY & PLAYBACK SYNC LAYER (SoundCloud Style)
	SyncPlaybackTelemetry(ctx context.Context, in *PlaybackTelemetryRequest, opts ...grpc.CallOption) (*PlaybackTelemetryResponse, error)
	GetRecentlyPlayed(ctx context.Context, in *RecentlyPlayedRequest, opts ...grpc.CallOption) (*RecentlyPlayedResponse, error)
	// 📁 USER LIBRARY & PLAYLIST LAYER
	SetTrackInteraction(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*InteractionResponse, error)
	CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*PlaylistResponse, error)
	AddToPlaylist(ctx context.Context, in *PlaylistTrackRequest, opts ...grpc.CallOption) (*PlaylistActionResponse, error)
}

type trackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackServiceClient(cc grpc.ClientConnInterface) TrackServiceClient {
	return &trackServiceClient{cc}
}

func (c *trackServiceClient) SearchTrack(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, TrackService_SearchTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetStreamURL(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamResponse)
	err := c.cc.Invoke(ctx, TrackService_GetStreamURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetTrendingTracks(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingResponse)
	err := c.cc.Invoke(ctx, TrackService_GetTrendingTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) SyncPlaybackTelemetry(ctx context.Context, in *PlaybackTelemetryRequest, opts ...grpc.CallOption) (*PlaybackTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackTelemetryResponse)
	err := c.cc.Invoke(ctx, TrackService_SyncPlaybackTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) GetRecentlyPlayed(ctx context.Context, in *RecentlyPlayedRequest, opts ...grpc.CallOption) (*RecentlyPlayedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecentlyPlayedResponse)
	err := c.cc.Invoke(ctx, TrackService_GetRecentlyPlayed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) SetTrackInteraction(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*InteractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractionResponse)
	err := c.cc.Invoke(ctx, TrackService_SetTrackInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) CreatePlaylist(ctx context.Context, in *CreatePlaylistRequest, opts ...grpc.CallOption) (*PlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaylistResponse)
	err := c.cc.Invoke(ctx, TrackService_CreatePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) AddToPlaylist(ctx context.Context, in *PlaylistTrackRequest, opts ...grpc.CallOption) (*PlaylistActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaylistActionResponse)
	err := c.cc.Invoke(ctx, TrackService_AddToPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackServiceServer is the server API for TrackService service.
// All implementations must embed UnimplementedTrackServiceServer
// for forward compatibility.
//
// Service managing track playback metadata, streaming sessions, and user interactions
type TrackServiceServer interface {
	// 🔍 TRACK DISCOVERY LAYER
	SearchTrack(context.Context, *SearchRequest) (*SearchResponse, error)
	GetStreamURL(context.Context, *StreamRequest) (*StreamResponse, error)
	GetTrendingTracks(context.Context, *TrendingRequest) (*TrendingResponse, error)
	// 🔄 TELEMETRY & PLAYBACK SYNC LAYER (SoundCloud Style)
	SyncPlaybackTelemetry(context.Context, *PlaybackTelemetryRequest) (*PlaybackTelemetryResponse, error)
	GetRecentlyPlayed(context.Context, *RecentlyPlayedRequest) (*RecentlyPlayedResponse, error)
	// 📁 USER LIBRARY & PLAYLIST LAYER
	SetTrackInteraction(context.Context, *InteractionRequest) (*InteractionResponse, error)
	CreatePlaylist(context.Context, *CreatePlaylistRequest) (*PlaylistResponse, error)
	AddToPlaylist(context.Context, *PlaylistTrackRequest) (*PlaylistActionResponse, error)
	mustEmbedUnimplementedTrackServiceServer()
}

// UnimplementedTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackServiceServer struct{}

func (UnimplementedTrackServiceServer) SearchTrack(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTrack not implemented")
}
func (UnimplementedTrackServiceServer) GetStreamURL(context.Context, *StreamRequest) (*StreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamURL not implemented")
}
func (UnimplementedTrackServiceServer) GetTrendingTracks(context.Context, *TrendingRequest) (*TrendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingTracks not implemented")
}
func (UnimplementedTrackServiceServer) SyncPlaybackTelemetry(context.Context, *PlaybackTelemetryRequest) (*PlaybackTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPlaybackTelemetry not implemented")
}
func (UnimplementedTrackServiceServer) GetRecentlyPlayed(context.Context, *RecentlyPlayedRequest) (*RecentlyPlayedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentlyPlayed not implemented")
}
func (UnimplementedTrackServiceServer) SetTrackInteraction(context.Context, *InteractionRequest) (*InteractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrackInteraction not implemented")
}
func (UnimplementedTrackServiceServer) CreatePlaylist(context.Context, *CreatePlaylistRequest) (*PlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlaylist not implemented")
}
func (UnimplementedTrackServiceServer) AddToPlaylist(context.Context, *PlaylistTrackRequest) (*PlaylistActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToPlaylist not implemented")
}
func (UnimplementedTrackServiceServer) mustEmbedUnimplementedTrackServiceServer() {}
func (UnimplementedTrackServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackServiceServer will
// result in compilation errors.
type UnsafeTrackServiceServer interface {
	mustEmbedUnimplementedTrackServiceServer()
}

func RegisterTrackServiceServer(s grpc.ServiceRegistrar, srv TrackServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackService_ServiceDesc, srv)
}

func _TrackService_SearchTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).SearchTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_SearchTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).SearchTrack(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetStreamURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetStreamURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetStreamURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetStreamURL(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetTrendingTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetTrendingTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetTrendingTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetTrendingTracks(ctx, req.(*TrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_SyncPlaybackTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaybackTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).SyncPlaybackTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_SyncPlaybackTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).SyncPlaybackTelemetry(ctx, req.(*PlaybackTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_GetRecentlyPlayed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentlyPlayedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).GetRecentlyPlayed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_GetRecentlyPlayed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).GetRecentlyPlayed(ctx, req.(*RecentlyPlayedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_SetTrackInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).SetTrackInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_SetTrackInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).SetTrackInteraction(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_CreatePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).CreatePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_CreatePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).CreatePlaylist(ctx, req.(*CreatePlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_AddToPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).AddToPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_AddToPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).AddToPlaylist(ctx, req.(*PlaylistTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackService_ServiceDesc is the grpc.ServiceDesc for TrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "track.TrackService",
	HandlerType: (*TrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTrack",
			Handler:    _TrackService_SearchTrack_Handler,
		},
		{
			MethodName: "GetStreamURL",
			Handler:    _TrackService_GetStreamURL_Handler,
		},
		{
			MethodName: "GetTrendingTracks",
			Handler:    _TrackService_GetTrendingTracks_Handler,
		},
		{
			MethodName: "SyncPlaybackTelemetry",
			Handler:    _TrackService_SyncPlaybackTelemetry_Handler,
		},
		{
			MethodName: "GetRecentlyPlayed",
			Handler:    _TrackService_GetRecentlyPlayed_Handler,
		},
		{
			MethodName: "SetTrackInteraction",
			Handler:    _TrackService_SetTrackInteraction_Handler,
		},
		{
			MethodName: "CreatePlaylist",
			Handler:    _TrackService_CreatePlaylist_Handler,
		},
		{
			MethodName: "AddToPlaylist",
			Handler:    _TrackService_AddToPlaylist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "track/track.proto",
}
