// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ListeningHistory struct {
	ID              int64     `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	TrackID         string    `json:"track_id"`
	LastPositionSec int32     `json:"last_position_sec"`
	IsCompleted     bool      `json:"is_completed"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Playlist struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Name          string         `json:"name"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	IsPrivate     bool           `json:"is_private"`
	CreatedAt     time.Time      `json:"created_at"`
}

type PlaylistTrack struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	TrackID    string    `json:"track_id"`
	AddedAt    time.Time `json:"added_at"`
}

type Track struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	ArtistID     string    `json:"artist_id"`
	ArtistName   string    `json:"artist_name"`
	Duration     string    `json:"duration"`
	ThumbnailUrl string    `json:"thumbnail_url"`
	YoutubeID    string    `json:"youtube_id"`
	PlayCount    int32     `json:"play_count"`
	LikesCount   int32     `json:"likes_count"`
	CreatedAt    time.Time `json:"created_at"`
}

type TrackInteraction struct {
	UserID       uuid.UUID `json:"user_id"`
	TrackID      string    `json:"track_id"`
	IsLiked      bool      `json:"is_liked"`
	InteractedAt time.Time `json:"interacted_at"`
}
