// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteTrackInteraction(ctx context.Context, arg DeleteTrackInteractionParams) error
	GetRecentlyPlayed(ctx context.Context, arg GetRecentlyPlayedParams) ([]GetRecentlyPlayedRow, error)
	GetTrack(ctx context.Context, id string) (Track, error)
	GetTrendingTracks(ctx context.Context, limit int32) ([]Track, error)
	SetTrackInteraction(ctx context.Context, arg SetTrackInteractionParams) error
	SyncPlaybackTelemetry(ctx context.Context, arg SyncPlaybackTelemetryParams) error
	UpdateTrackStats(ctx context.Context, arg UpdateTrackStatsParams) error
}

var _ Querier = (*Queries)(nil)
