// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTrackInteraction = `-- name: DeleteTrackInteraction :exec
DELETE FROM track_interactions 
WHERE user_id = $1 AND track_id = $2
`

type DeleteTrackInteractionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	TrackID string    `json:"track_id"`
}

func (q *Queries) DeleteTrackInteraction(ctx context.Context, arg DeleteTrackInteractionParams) error {
	_, err := q.db.ExecContext(ctx, deleteTrackInteraction, arg.UserID, arg.TrackID)
	return err
}

const getRecentlyPlayed = `-- name: GetRecentlyPlayed :many
SELECT t.id, t.title, t.artist_id, t.artist_name, t.duration, t.thumbnail_url, t.youtube_id, t.play_count, t.likes_count, t.created_at, lh.last_position_sec, lh.updated_at
FROM listening_history lh
JOIN tracks t ON lh.track_id = t.id
WHERE lh.user_id = $1
ORDER BY lh.updated_at DESC
LIMIT $2
`

type GetRecentlyPlayedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type GetRecentlyPlayedRow struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	ArtistID        string    `json:"artist_id"`
	ArtistName      string    `json:"artist_name"`
	Duration        string    `json:"duration"`
	ThumbnailUrl    string    `json:"thumbnail_url"`
	YoutubeID       string    `json:"youtube_id"`
	PlayCount       int32     `json:"play_count"`
	LikesCount      int32     `json:"likes_count"`
	CreatedAt       time.Time `json:"created_at"`
	LastPositionSec int32     `json:"last_position_sec"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetRecentlyPlayed(ctx context.Context, arg GetRecentlyPlayedParams) ([]GetRecentlyPlayedRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentlyPlayed, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyPlayedRow
	for rows.Next() {
		var i GetRecentlyPlayedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.Duration,
			&i.ThumbnailUrl,
			&i.YoutubeID,
			&i.PlayCount,
			&i.LikesCount,
			&i.CreatedAt,
			&i.LastPositionSec,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrack = `-- name: GetTrack :one
SELECT id, title, artist_id, artist_name, duration, thumbnail_url, youtube_id, play_count, likes_count, created_at FROM tracks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTrack(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ArtistName,
		&i.Duration,
		&i.ThumbnailUrl,
		&i.YoutubeID,
		&i.PlayCount,
		&i.LikesCount,
		&i.CreatedAt,
	)
	return i, err
}

const getTrendingTracks = `-- name: GetTrendingTracks :many
SELECT id, title, artist_id, artist_name, duration, thumbnail_url, youtube_id, play_count, likes_count, created_at FROM tracks
ORDER BY play_count DESC, likes_count DESC
LIMIT $1
`

func (q *Queries) GetTrendingTracks(ctx context.Context, limit int32) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getTrendingTracks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.Duration,
			&i.ThumbnailUrl,
			&i.YoutubeID,
			&i.PlayCount,
			&i.LikesCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrackInteraction = `-- name: SetTrackInteraction :exec
INSERT INTO track_interactions (user_id, track_id, is_liked, interacted_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id, track_id) 
DO UPDATE SET is_liked = EXCLUDED.is_liked, interacted_at = now()
`

type SetTrackInteractionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	TrackID string    `json:"track_id"`
	IsLiked bool      `json:"is_liked"`
}

func (q *Queries) SetTrackInteraction(ctx context.Context, arg SetTrackInteractionParams) error {
	_, err := q.db.ExecContext(ctx, setTrackInteraction, arg.UserID, arg.TrackID, arg.IsLiked)
	return err
}

const syncPlaybackTelemetry = `-- name: SyncPlaybackTelemetry :exec
INSERT INTO listening_history (user_id, track_id, last_position_sec, is_completed, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, track_id) 
DO UPDATE SET last_position_sec = EXCLUDED.last_position_sec, is_completed = EXCLUDED.is_completed, updated_at = now()
`

type SyncPlaybackTelemetryParams struct {
	UserID          uuid.UUID `json:"user_id"`
	TrackID         string    `json:"track_id"`
	LastPositionSec int32     `json:"last_position_sec"`
	IsCompleted     bool      `json:"is_completed"`
}

func (q *Queries) SyncPlaybackTelemetry(ctx context.Context, arg SyncPlaybackTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, syncPlaybackTelemetry,
		arg.UserID,
		arg.TrackID,
		arg.LastPositionSec,
		arg.IsCompleted,
	)
	return err
}

const updateTrackStats = `-- name: UpdateTrackStats :exec
UPDATE tracks 
SET play_count = play_count + $1::integer, 
    likes_count = likes_count + $2::integer
WHERE id = $3
`

type UpdateTrackStatsParams struct {
	PlayCountChange  int32  `json:"play_count_change"`
	LikesCountChange int32  `json:"likes_count_change"`
	TrackID          string `json:"track_id"`
}

func (q *Queries) UpdateTrackStats(ctx context.Context, arg UpdateTrackStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateTrackStats, arg.PlayCountChange, arg.LikesCountChange, arg.TrackID)
	return err
}
