apiVersion: v1
kind: ConfigMap
metadata:
  name: phonkdrift-config
  namespace: default
data:
  API_GATEWAY_HTTP_PORT: "8080"
  API_GATEWAY_GRPC_PORT: "50050"
  AUTH_GRPC_PORT: "50051"
  TRACK_GRPC_PORT: "50052"
  CHAT_GRPC_PORT: "50053"
  AUTH_SERVICE_ADDR: "auth-service:50051"
  TRACK_SERVICE_ADDR: "track-service:50052"
  CHAT_SERVICE_ADDR: "chat-service:50053"
  REDIS_ADDR: "redis-service:6379"
  RABBITMQ_FALLBACK_URL: "amqp://guest:guest@rabbitmq-service:5672/"
  DO_SPACES_BUCKET: "phonkdrift-storage"
  DO_SPACES_ENDPOINT: "https://fra1.digitaloceanspaces.com"
  DO_SPACES_CDN_URL: "https://phonkdrift-storage.fra1.cdn.digitaloceanspaces.com"
  YT_DLP_COOKIES_PATH: "/app/cookies/cookies.txt"
  VERSION_FILE_PATH: "/app/version.json"
