apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # 1 Gigabyte is plenty for text-based URL cache strings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"] # 💡 Tells Redis to continuously save data to disk
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data # Redis container default data persistence directory
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-data-pvc