// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCommunityMembers = `-- name: CountCommunityMembers :one
SELECT COUNT(*) FROM community_members
`

func (q *Queries) CountCommunityMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommunityMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages (user_id, username, avatar_url, content, media_url, message_type, reply_to_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, username, avatar_url, content, media_url, message_type, reply_to_id, created_at
`

type CreateMessageParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Username    string         `json:"username"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Content     sql.NullString `json:"content"`
	MediaUrl    sql.NullString `json:"media_url"`
	MessageType string         `json:"message_type"`
	ReplyToID   uuid.NullUUID  `json:"reply_to_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.UserID,
		arg.Username,
		arg.AvatarUrl,
		arg.Content,
		arg.MediaUrl,
		arg.MessageType,
		arg.ReplyToID,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Content,
		&i.MediaUrl,
		&i.MessageType,
		&i.ReplyToID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, user_id, username, avatar_url, content, media_url, message_type, reply_to_id, created_at FROM chat_messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Content,
		&i.MediaUrl,
		&i.MessageType,
		&i.ReplyToID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesBefore = `-- name: GetMessagesBefore :many
SELECT id, user_id, username, avatar_url, content, media_url, message_type, reply_to_id, created_at FROM chat_messages
WHERE created_at < $1
ORDER BY created_at DESC
LIMIT $2
`

type GetMessagesBeforeParams struct {
	CreatedAt sql.NullTime `json:"created_at"`
	Limit     int32        `json:"limit"`
}

func (q *Queries) GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBefore, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Content,
			&i.MediaUrl,
			&i.MessageType,
			&i.ReplyToID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isCommunityMember = `-- name: IsCommunityMember :one
SELECT EXISTS(SELECT 1 FROM community_members WHERE user_id = $1) AS is_member
`

func (q *Queries) IsCommunityMember(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, isCommunityMember, userID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const joinCommunity = `-- name: JoinCommunity :one
INSERT INTO community_members (user_id, username, avatar_url) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id
`

type JoinCommunityParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) JoinCommunity(ctx context.Context, arg JoinCommunityParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, joinCommunity, arg.UserID, arg.Username, arg.AvatarUrl)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const leaveCommunity = `-- name: LeaveCommunity :exec
DELETE FROM community_members WHERE user_id = $1
`

func (q *Queries) LeaveCommunity(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, leaveCommunity, userID)
	return err
}

const listCommunityMembers = `-- name: ListCommunityMembers :many
SELECT user_id, username, avatar_url, joined_at,
       ROW_NUMBER() OVER (ORDER BY joined_at ASC) AS join_rank
FROM community_members
ORDER BY joined_at ASC
LIMIT $1 OFFSET $2
`

type ListCommunityMembersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCommunityMembersRow struct {
	UserID    uuid.UUID      `json:"user_id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	JoinedAt  sql.NullTime   `json:"joined_at"`
	JoinRank  int64          `json:"join_rank"`
}

func (q *Queries) ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityMembers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunityMembersRow
	for rows.Next() {
		var i ListCommunityMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.JoinedAt,
			&i.JoinRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
