// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type ChatMessage struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Username    string         `json:"username"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Content     sql.NullString `json:"content"`
	MediaUrl    sql.NullString `json:"media_url"`
	MessageType string         `json:"message_type"`
	ReplyToID   uuid.NullUUID  `json:"reply_to_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type CommunityMember struct {
	UserID    uuid.UUID      `json:"user_id"`
	JoinedAt  sql.NullTime   `json:"joined_at"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}
