// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountCommunityMembers(ctx context.Context) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (ChatMessage, error)
	GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]ChatMessage, error)
	IsCommunityMember(ctx context.Context, userID uuid.UUID) (bool, error)
	JoinCommunity(ctx context.Context, arg JoinCommunityParams) (uuid.UUID, error)
	LeaveCommunity(ctx context.Context, userID uuid.UUID) error
	ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error)
}

var _ Querier = (*Queries)(nil)
